# Generated by Django 5.2 on 2025-04-21 00:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_city_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_km', models.FloatField()),
                ('end_km', models.FloatField()),
                ('status', models.CharField(choices=[('good', 'Bon état'), ('works', 'En travaux'), ('slow', 'Limitation de vitesse')], max_length=100)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='RestApi.road')),
            ],
        ),
    ]
